
## Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]

## Switches
set_property PACKAGE_PIN V17 [get_ports {FREQ_DIV[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[0]}]
set_property PACKAGE_PIN V16 [get_ports {FREQ_DIV[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[1]}]
set_property PACKAGE_PIN W16 [get_ports {FREQ_DIV[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[2]}]
set_property PACKAGE_PIN W17 [get_ports {FREQ_DIV[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[3]}]
set_property PACKAGE_PIN W15 [get_ports {FREQ_DIV[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[4]}]
set_property PACKAGE_PIN V15 [get_ports {FREQ_DIV[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[5]}]
set_property PACKAGE_PIN W14 [get_ports {FREQ_DIV[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[6]}]
set_property PACKAGE_PIN W13 [get_ports {FREQ_DIV[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[7]}]
set_property PACKAGE_PIN V2 [get_ports {FREQ_DIV[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[8]}]
set_property PACKAGE_PIN T3 [get_ports {FREQ_DIV[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[9]}]
set_property PACKAGE_PIN T2 [get_ports {FREQ_DIV[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[10]}]
set_property PACKAGE_PIN R3 [get_ports {FREQ_DIV[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[11]}]
set_property PACKAGE_PIN W2 [get_ports {FREQ_DIV[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[12]}]
set_property PACKAGE_PIN U1 [get_ports {FREQ_DIV[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[13]}]

## LEDs
# set_property PACKAGE_PIN U16 [get_ports {FREQ_DIV[0]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[0]}]
# set_property PACKAGE_PIN E19 [get_ports {FREQ_DIV[1]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[1]}]
# set_property PACKAGE_PIN U19 [get_ports {FREQ_DIV[2]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[2]}]
# set_property PACKAGE_PIN V19 [get_ports {FREQ_DIV[3]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[3]}]
# set_property PACKAGE_PIN W18 [get_ports {FREQ_DIV[4]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[4]}]
# set_property PACKAGE_PIN U15 [get_ports {FREQ_DIV[5]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[5]}]
# set_property PACKAGE_PIN U14 [get_ports {FREQ_DIV[6]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[6]}]
# set_property PACKAGE_PIN V14 [get_ports {FREQ_DIV[7]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[7]}]
# set_property PACKAGE_PIN V13 [get_ports {FREQ_DIV[8]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[8]}]
# set_property PACKAGE_PIN V3 [get_ports {FREQ_DIV[9]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[9]}]
# set_property PACKAGE_PIN W3 [get_ports {FREQ_DIV[10]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[10]}]
# set_property PACKAGE_PIN U3 [get_ports {FREQ_DIV[11]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[11]}]
# set_property PACKAGE_PIN P3 [get_ports {FREQ_DIV[12]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[12]}]
# set_property PACKAGE_PIN N3 [get_ports {FREQ_DIV[13]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {FREQ_DIV[13]}]

##7 segment display
set_property PACKAGE_PIN W7 [get_ports {DISPLAY[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[7]}]
set_property PACKAGE_PIN W6 [get_ports {DISPLAY[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[6]}]
set_property PACKAGE_PIN U8 [get_ports {DISPLAY[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[5]}]
set_property PACKAGE_PIN V8 [get_ports {DISPLAY[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[4]}]
set_property PACKAGE_PIN U5 [get_ports {DISPLAY[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[3]}]
set_property PACKAGE_PIN V5 [get_ports {DISPLAY[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[2]}]
set_property PACKAGE_PIN U7 [get_ports {DISPLAY[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[1]}]

set_property PACKAGE_PIN V7 [get_ports {DISPLAY[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {DISPLAY[0]}]

set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]

##Pmod Header JA
##Sch name = JA1
set_property PACKAGE_PIN J1 [get_ports PULSES]
	set_property IOSTANDARD LVCMOS33 [get_ports PULSES]
